# Generated by Django 4.2.19 on 2025-06-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_favorite_recipe_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': 'favorite_by', 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
